language: cpp
cache:
  ccache: true
  pip: true

matrix:
  include:
    ## CMake Build Generator

    # Linux, AMD64
    - os: linux
      dist: xenial
      compiler: gcc
      env: BUILDER=cmake ARCH=amd64
    - os: linux
      dist: xenial
      compiler: clang
      env: BUILDER=cmake ARCH=amd64

    # Mac OS X, AMD64
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      env: BUILDER=cmake ARCH=amd64
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: BUILDER=cmake ARCH=amd64

install:
  - ./.travis/install.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; fi

script:
  - ./.travis/script.sh
